<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>CKPNLibrary</AssemblyName>
    <RootNamespace>CKPNLibrary</RootNamespace>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>7.3</LangVersion>
    <!-- AnyCPU: Excel-DNA otomatis generate XLL untuk 32-bit DAN 64-bit -->
    <PlatformTarget>AnyCPU</PlatformTarget>
    <Optimize>true</Optimize>
    <DebugType>none</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ExcelDna.AddIn"                 Version="1.8.0" />
    <PackageReference Include="Microsoft.Office.Interop.Excel" Version="15.0.4795.1000" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System" />
    <Reference Include="System.Core" />
  </ItemGroup>

</Project>